#!/usr/bin/env bash

function Alarm() {
  notify-send --urgency critical "$1"
}

function Sleep() {
  ## TODO: validate format hh:mm:ss.SSS
  separators=$(echo "$2" | tr --delete --complement ':' | wc -c )
  
  echo $separators
  
  case $separators in
  	0)
  		seconds="$2"
  		;;
  	1)
  		seconds=$(echo "$2" | awk -F: '{ print ($1 * 60) + $2 }')
  		;;
  	2)
  		seconds=$(echo "$2" | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
  		;;
  esac
  
  echo $seconds
  
  sleep "$seconds"
}

if [[ $* -lt 2 ]]
then
  Alarm ${1:-"Finished"}
else
  Sleep $@
  Alarm $1
fi

