#!/usr/bin/env zsh

for i in "$@"; do
    case "$i" in
        '0x'*)
            echo "hex ${i:2}"
            j=$((16#${i:2}))
            ;;
        '0b'*)
            echo "bin ${i:2}"
            j=$((2#${i:2}))
            ;;
        '0'*)
            echo "oct ${i:1}"
            j=$((8#${i:1}))
            ;;
        *)
            echo "dec ${i}"
            j=$i
            ;;
    esac

    echo -n '0b' ; cprintf '{#m}\n' "$(([##2]j))"
    echo -n ' 0' ; cprintf '{#c}\n' "$(([##8]j))"
    echo -n '  ' ; cprintf '{#g}\n' "$(([##10]j))"
    echo -n '0x' ; cprintf '{#y}\n' "$(([##16]j))"

    echo
done


