#!/usr/bin/env bash

git for-each-ref --sort=committerdate --format='%(committerdate:iso8601) %(refname:short)' refs/heads/ | \
	fzf --multi | \
	cut -d\  -f4 | \
	while read -r line; do 
		git branch -D $line;
       	done | \
	tee /tmp/deleted-git-branches-$RANDOM

# note: to restore a branch: check the tee-ed file and re-assign the branch to that commit

