#!/usr/bin/env bash

for f in $(ls -1); do
    again=true

    while $again; do

        c "$f"

        echo -n "What to do with $f? "
        cprintf '{#red}' "(d)elete "
        echo -n "(k)eep "
        echo -n "watch a(g)ain "

        read choice

        case $choice in
            d*)
                rm -v "$f"
                cprintf '{#red}\n' Deleted
                again=false
                ;;
            k*)
                cprintf '{#green}\n' Kept
                again=false
                ;;
            g*)
                c "$f"
                ;;
        esac
    done 
done
