#!/bin/sh
# adapted from https://github.com/LukeSmithxyz/voidrice/blob/9524786a864ee3614e37ab260e413c3eaadf78fd/.scripts/i3cmds/dmenuunicode
# Give rofi list of all unicode characters to copy.
# Arch emoki support: sudo pacman -S noto-fonts-emoji

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
list="$SCRIPT_DIR/../../resources/emoji"

chosen=$(grep -v "#" "$list" | rofi -i -dmenu -font 'Noto Sans 32' )

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip
