#!/usr/bin/env bash

choice="$(cut -d\| -f1 < "$HOME"/.resources/menu | rofi -i -dmenu)"

if [ ! -z "$choice" ]; then 
	script="$(grep "$choice|" < "$HOME"/.resources/menu | cut -d\| -f2)"
fi

$script
