#!/usr/bin/env bash

xclip -o -selection primary | xclip -i -selection clipboard

i3-msg workspace number 2
sleep 0.2

xdotool key "control+shift+f"
sleep 0.2

xdotool key "control+v"
sleep 0.5

xdotool key "enter"

