#!/usr/bin/env bash

FCITX_AVAILABLE="$(command -v fcitx5-remote)"
FCITX_RUNNING="$(fcitx5-remote)"
if [[ -n $FCITX_AVAILABLE && FCITX_RUNNING -gt 0 ]]; then
  USE_FCITX=true
else
  USE_FCITX=false
fi

notify-send "Switching to $1"

case "$1" in
  'us')
    if [[ $USE_FCITX = 'true' ]]; then
      fcitx5-remote -T
      fcitx5-remote -s 'keyboard-us'
      setxkbmap us
    else
      setxkbmap us
    fi
    ;;

  'fr')
    if [[ $USE_FCITX = 'true' ]]; then
      fcitx5-remote -t
      fcitx5-remote -s 'keyboard-fr'
    else
      setxkbmap fr
    fi
    ;;

  'de')
    if [[ $USE_FCITX = 'true' ]]; then
      fcitx5-remote -T
      #fcitx5-remote -s 'keyboard-de'
      setxkbmap de
    else
      setxkbmap de
    fi
    ;;

  'jp')
    if [[ $USE_FCITX = 'true' ]]; then
      fcitx5-remote -t
      fcitx5-remote -s 'mozc'
    else
      notify-send --app-name 'Keyboard Switch' --urgency normal ' ' 'Missing fcitx input method switcher'
    fi
    ;;

esac
