[font]
size = 10.0
offset = { x = 0, y = 2 }

[font.bold]
family = "FiraCode Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Propo"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Propo"
style = "Regular"
