[font]
size = 7.0
offset = { x = 0, y = 2 }

[font.bold]
family = "Furi Code"
style = "Bold"

[font.bold_italic]
family = "Furi Code"
style = "Bold Italic"

[font.italic]
family = "Furi Code"
style = "Italic"

[font.normal]
family = "Furi Code"
style = "Regular"


