[font]
size = 10.0

[font.bold]
family = "Source Code Pro Black"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro BlackIt"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro It"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"
