- name: "CPP dev tools"
  block:
    - name: "Ubuntu CPP tools"
      package:
        name:
          - g++
          - ccache
          - cmake
          - build-essential
          - qtbase5-dev
          - qttools5-dev-tools
          - libqt5svg5-dev
          - qttools5-dev
          - libqt5dbus5
          - libqt5network5
          - libqt5core5a
          - libqt5widgets5
          - libqt5gui5
          - libqt5svg5
        state: latest
