---
- include_tasks: essentials.yml
- include_tasks: zsh.yml
- include_tasks: rust.yml
- include_tasks: git_install.yml
- include_tasks: git_config.yml
- include_tasks: user.yml
- include_tasks: python.yml

  
# TODO: check if this is now handled by the custom installer
#- include_tasks: sensors.yml

