- name: "User scripts install"
  block:
    - name: "Custom scripts"
      ansible.builtin.file:
        src: "/home/{{ current_user }}/dev/ununhexium/configfiles/.local/scripts"
        dest: "/home/{{ current_user }}/.local/scripts"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        state: link
