- name: "Zsh"
  block:
    - name: "Zsh packages"
      ansible.builtin.package:
        name:
          - zsh
          - zsh-antigen
        state: latest

    - name: ".zshrc"
      file:
        src: "{{ playbook_dir }}/roles/cli/files/.zshrc"
        dest: "/home/{{ current_user }}/.zshrc"
        state: link

    - name: ".zshrc.d"
      ansible.builtin.file:
        path: "/home/{{ current_user }}/.zshrc.d"
        state: directory
        mode: '0755'
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: "user.zsh"
      file:
        src: "{{ playbook_dir }}/roles/cli/files/.zshrc.d/user.zsh"
        dest: "/home/{{ current_user }}/.zshrc.d/user.zsh"
        state: link

    - name: "Powerline 10k"
      file:
        src: "{{ playbook_dir }}/roles/cli/files/.zshrc.d/p10k.zsh"
        dest: "/home/{{ current_user }}/.zshrc.d/p10k.zsh"
        state: link

    - name: "ZSH syntax highlight"
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
        dest: "/home/{{ current_user }}/dev/zsh-users/zsh-syntax-highlighting/"
        clone: yes
        update: yes
        version: "0.7.1"
