
- name: Install the essential packages
  block:

    - name: "apt-file"
      block:
        - name: "apt-file package"
          ansible.builtin.package:
            name: apt-file
            state: latest
        - name: "apt-file update"
          ansible.builtin.shell: "apt-file update"

    - name: "Custom scripts"
      ansible.builtin.file:
        src: "/home/{{ current_user }}/dev/ununhexium/configfiles/.local/scripts"
        dest: "/home/{{ current_user }}/.local/scripts"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        state: link

    - name: "Git config"
      ansible.builtin.copy:
        src: ".gitconfig"
        dest: "/home/{{ current_user }}/.gitconfig"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: "Zsh"
      include: zsh.yml

    - name: "Others"
      ansible.builtin.package:
        name:
          - apt-file
          - bat
          - chafa
          - exa
          - fzf
          - htop
          - iftop
          - redshift
          - redshift-gtk
          - speedometer
          - vim
        state: latest
