- name: "Rust"
  block:
    - name: "Check if cargo is installed"
      shell: "test -f /home/{{ current_user }}/.cargo/bin/cargo"
      become_user: "{{ current_user }}"
      register: cargo_exists
      ignore_errors: yes

    - name: "Download Rustup Installer"
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: "Install rust/cargo"
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: "Enable cargo in ZSH"
      when: cargo_exists is failed
      ansible.builtin.lineinfile:
        path: "/home/{{ current_user }}/.zsh.ansible"
        create: yes
        line: "[ -f $HOME/.cargo/env ] && source $HOME/.cargo/env"

    - name: "Install bat"
      shell: "cargo install bat"

    - name: "Install git delta"
      shell: "cargo install git-delta"
