#!/bin/bash

current=$(cat /sys/class/backlight/intel_backlight/brightness)
max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
levels=(  )
levels_count=${#levels[@]}

index=$(echo "(($current-1) * $levels_count / $max)" | bc)

echo ${levels[$index]}

