#!/usr/bin/env bash

function show_usage() {

    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    source "$DIR/cpu_usage_location.sh"
    # cpu_usage=$(echo "scale=1 ; 100 - "$(mpstat 1 1 -o JSON | jq '.sysstat.hosts[0].statistics[0]."cpu-load"[0].idle') | bc)
    "$DIR/refresh_cpu_usage.sh" &
    cpu_usage=$(cat "$cpu_usage_location") || exit 1
    load=$(cat "/proc/loadavg" | cut -d' ' -f1)
    count=$(cat "/proc/cpuinfo" | grep processor | wc -l)
    
    high=$(echo "scale=1 ; $count / 2" | bc)
    warn=$(echo "scale=1 ; $count / 2 + $count / 4" | bc)
    crit=$count
    
    
    # Print short_text, full_text
    echo "$cpu_usage%"
    echo "H $high W $warn C $crit"
    
    # Print color, if needed
    [[ $(echo "$load > $crit" | bc -l) == 1 ]] && echo "#FF00FF" && exit 0
    [[ $(echo "$load > $warn" | bc -l) == 1 ]] && echo "#FFFF00" && exit 0
    [[ $(echo "$load > $high" | bc -l) == 1 ]] && echo "#00FFFF" && exit 0

}


case $BLOCK_BUTTON in
    1)
        name=cpu_usage_click
        terminator -T $name -e "htop --sort-key PERCENT_CPU" &
        # Dirty hack to give time to terminator to start
        while [ -z "$ID" ]; do
            ID=$(xdotool search --name $name)
        done
        xdotool windowmove $ID $(expr $BLOCK_X - 500) 100
        xdotool windowsize $ID 1000 700

        # Close htop cleanly
        xdotool search --name $name behave %@ blur windowfocus key F10
        xdotool keyup F10
        ;;
esac

show_usage


exit 0;
