#!/usr/bin/env bash

# to hold the result of extract
ext=""

function extract() {
    ext=$(cat /proc/meminfo | grep "$1" | sed -E -e 's/ +/-/g' | cut -d- -f2)
}

extract "MemAvailable"
kb="$ext"
#kb="4456789"
gb=$(echo "scale=1 ; $kb / 1024 / 1024" | bc)

extract "MemTotal"
total=$ext
usage=$(echo "$kb * 100 / $total" | bc)

high=50
warn=25
crit=10

echo $gb GB
echo $gb GB

[[ "$usage" -lt "$crit" ]] && echo "#FF00FF" && exit 0
[[ "$usage" -lt "$warn" ]] && echo "#FFFF00" && exit 0
[[ "$usage" -lt "$high" ]] && echo "#00FFFF" && exit 0

exit 0
