#!/usr/bin/env bash

if [[ $(cat /sys/devices/system/cpu/cpufreq/boost) -eq 1 ]]; then
    echo '<span foreground="lime"></span>'
else
    echo '<span foreground="cyan"></span>'
fi

case $BLOCK_BUTTON in
    1)
        if [ $(cat /sys/devices/system/cpu/cpufreq/boost) -eq 1 ]; then
            echo "0" | pkexec tee /sys/devices/system/cpu/cpufreq/boost
        else
            echo "1" | pkexec tee /sys/devices/system/cpu/cpufreq/boost
        fi
        ;;
esac


