#!/usr/bin/env bash

# From https://github.com/adi1090x/rofi/blob/master/1080p/bin/usedcpu

PREV_TOTAL=0
PREV_IDLE=0

#! use tmpfs
cpuFile="/tmp/.cpu"

if [[ -f "${cpuFile}" ]]; then
  fileCont=$(cat "${cpuFile}")
  PREV_TOTAL=$(echo "${fileCont}" | head -n 1)
  PREV_IDLE=$(echo "${fileCont}" | tail -n 1)
fi

CPU=(`cat /proc/stat | grep '^cpu '`) # Get the total CPU statistics.
unset CPU[0]                          # Discard the "cpu" prefix.
IDLE=${CPU[4]}                        # Get the idle CPU time.

# Calculate the total CPU time.
TOTAL=0

for VALUE in "${CPU[@]:0:4}"; do
  let "TOTAL=$TOTAL+$VALUE"
done

# Remember the total and idle CPU times for the next check.
echo "${TOTAL}" > "${cpuFile}"
echo "${IDLE}" >> "${cpuFile}"

if [[ "${PREV_TOTAL}" != "" ]] && [[ "${PREV_IDLE}" != "" ]]; then
  # Calculate the CPU usage since we last checked.
  let "DIFF_IDLE=$IDLE-$PREV_IDLE"
  let "DIFF_TOTAL=$TOTAL-$PREV_TOTAL"
  let "DIFF_USAGE=(1000*($DIFF_TOTAL-$DIFF_IDLE)/$DIFF_TOTAL+5)/10"

  graphite "monitoring.cpu.usage" "$DIFF_USAGE"

  COLOR="white"
  if [[ $DIFF_USAGE -gt 50 ]] ; then
    COLOR="cyan"
  fi 
  if [[ $DIFF_USAGE -gt 80 ]] ; then
    COLOR="yellow"
  fi
  if [[ $DIFF_USAGE -gt 95 ]] ; then
    COLOR="magenta"
  fi
  echo "  ${DIFF_USAGE}%"
else
    echo "  ?"
fi

