- name: "Discord"
  block:
    - name: Check if discord is present
      command: ls /usr/bin/discord
      register: discord_installed
      ignore_errors: yes

    - name: "Discord dependencies"
      ansible.builtin.package:
        name:
          - libgconf-2-4
          - libc++1
        state: latest
      when: discord_installed is failed

    - name: "Discord download"
      get_url:
        url: https://discord.com/api/download?platform=linux&format=deb
        dest: /tmp/discord.deb
        mode: '0400'
        force: 'yes'
      when: discord_installed is failed

    - name: "Discord deb install"
      ansible.builtin.apt:
        deb: /tmp/discord.deb
      when: discord_installed is failed
