
- name: Install the essential desktop packages
  become_user: root

  block:
    - name: "Others: apt GUI tools"
      ansible.builtin.package:
        name:
          - arandr
          - deluge
          - dunst
          - feh
          - flameshot
          - gimp
          - gource
          - imagemagick
          - kdiff3
          - libinput-tools
          - redshift-gtk
          - rofi
          - terminator
          - unclutter
          - vim-gui-common
          - vlc
          - xclip
          - xterm

        state: latest
