
- name: Install the essential desktop packages
  become_user: root

  block:
    - name: "Others: apt GUI tools"
      ansible.builtin.package:
        name:
          - arandr
          - compton
          - deluge
          - dunst
          - flameshot
          - gource
          - imagemagick
          - i3
          - i3blocks
          - kdiff3
          - redshift-gtk
          - rofi
          - terminator
          - unclutter
          - vim-gui-common
          - xterm

        state: latest
