#!/bin/bash

function show() {
	filename=$(basename -- "$1")
	extension="${filename##*.}"
	filename="${filename%.*}"

	case $extension in
		md) mdv $1
		;;
		*) pygmentize $1
		;;
	esac
}

while (( "$#" )); do
	show $1
	shift
done

