[greenclip]
history_file = "/home/uuh/.cache/greenclip.history"
max_history_length = 50
max_selection_size_bytes = 10000000
trim_space_from_selection = true
use_primary_selection_as_input = true
blacklisted_applications = []
enable_image_support = true
image_cache_directory = "/tmp/greenclip"
static_history = []
