---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    vars:
      current_username: "uuh"
    connection: local 
    tasks:
      - name: "Essentials"
        ansible.builtin.include: lib/essentials.yml

      - debug: var=current_username

      - name: "Cargo"
        block:
          - name: "Check if cargo is installed"
            shell: command -v cargo
            register: cargo_exists
            ignore_errors: yes

          - name: "Download Installer"
            when: cargo_exists is failed
            get_url:
              url: https://sh.rustup.rs
              dest: /tmp/sh.rustup.rs
              mode: '0755'
              force: 'yes'
            tags:
              - rust

          - name: "Install rust/cargo"
            when: cargo_exists is failed
            shell: /tmp/sh.rustup.rs -y
            tags:
              - rust

          - name: "Enable cargo in ZSH"
            when: cargo_exists is failed
            ansible.builtin.lineinfile:
              path: "/home/{{ current_username }}/.zsh.ansible"
              create: yes
              line: "[ -f $HOME/.cargo/env ] && source $HOME/.cargo/env"

      - name: "Git"
        block:
          - name: package
            ansible.builtin.package:
              name: git
              state: latest

