---
  - name: "Setup 116"
    hosts: localhost
    gather_facts: yes
    become_method: sudo

    roles:
      - role: ontic.fonts

      - role: gantsign.golang
        golang_gopath: '$HOME/.go'

      - role: Comcast.sdkman
        sdkman_user: "{{ current_user }}"
        sdkman_group: "{{ current_user }}"
        sdkman_auto_answer: true
        sdkman_update: true
        sdkman_install_packages:
          - candidate: gradle
#          - { candidate: java, version: 17.0.4-zulu }

      - role: cli

    vars:
      current_user: "uuh"

    connection: local
