---
  - name: "Setup 116"
    hosts: localhost
    roles:
      - { role: ontic.fonts }
    vars:
      current_user: "uuh"
    connection: local
    tasks:
      - name: "Essentials"
        ansible.builtin.include: roles/desktop/essentials.yml
        tags: essentials

      - name: "Rust"
        ansible.builtin.include: roles/desktop/rust.yml
        tags: rust

      - name: "Git"
        block:
          - name: package
            ansible.builtin.package:
              name: git
              state: latest

