#!/usr/bin/env python3


from openai import OpenAI
client = OpenAI()

response = client.responses.create(
    model="gpt-5-nano",
    input="Write a one-sentence bedtime story about a unicorn."
)


print("...")
print(response.output_text)
