#!/bin/sh

# Use FZF to select an apt package and install it

package=$(apt list 2> /dev/null | fzf --preview 'echo {} | cut -d/ -f1 | xargs apt show' | cut -d/ -f1)

if [ ! -z "$package" ]; then 
    sudo apt install "$package"
fi

echo ": $(date +%s):0;sudo apt install $package" >> ~/.zsh_history

exit 0

