#!/bin/sh

show_as_jar() {
    unzip -l "$1" && javaversion "$1"
}

show() {
	filename=$(basename -- "$1")
	extension="${filename##*.}"
	filename="${filename%.*}"
    filetype=$(file --brief --mime "$1")

    echo "Filetype: $filetype"

    case $filetype in

        application/java-archive*)
            show_as_jar "$1"
            ;;

        application/x-xz*)
            tar --list --verbose --file="$1"
            ;;

        application/zip*)
            case $extension in
                jar) show_as_jar "$1"
                    ;;
                *) unzip -l "$1"
                    ;;
            esac
            ;;

        inode/x-empty*)
            cecho blue "Empty file"
            ;;

        inode/directory*)
            lsd "$1"
            ;;

        text/*)
            case $extension in
                md) mdv "$1"
                    ;;
                *) pygmentize -Ostyle=friendly -g "$1"
                    ;;
            esac
            ;;

        *) cecho RED "Don't know how to best show $1"
            ;;
    esac
}

for file in "$@"; do
	show "$file"
done

