#!/bin/sh

show_as_jar() {
    unzip -l "$1" && javaversion "$1"
}

show() {
	filename=$(basename -- "$1")
	extension="${filename##*.}"
	filename="${filename%.*}"
    filetype=$(file --brief --mime "$1")

    #echo "Filetype: $filetype"

    case $filetype in

    	application/gzip*)
            tar tvf "$1"
            ;;

        application/java-archive*)
            show_as_jar "$1"
            ;;

        application/json*)
            bat "$1"
            ;;

        application/pdf*)
            mupdf "$1"
            ;;

        application/vnd.debian.binary-package*)
            dpkg --contents "$1"
            ;;

        application/x-xz*)
            tar --list --verbose --file="$1"
            ;;

        application/x-bzip2*)
            tar --bzip2 --list --verbose --file="$1"
            ;;

        application/zip*)
            case $extension in
                jar) show_as_jar "$1"
                    ;;
                *) unzip -l "$1"
                    ;;
            esac
            ;;

        image/*)
            feh --auto-zoom --fullscreen "$1"
            ;;

        inode/x-empty*)
            cecho blue "Empty file"
            ;;

        inode/directory*)
            lsd "$1"
            ;;

        inode/symlink*)
            c $(readlink -f "$1")
            ;;

        text/*)
            case $extension in
                md) mdv "$1"
                    ;;
                *) bat "$1"
                    ;;
            esac
            ;;

        video/*)
            vlc "$1" --fullscreen --play-and-exit
            ;;

        *) cecho RED "Don't know how to best show $1"
            ;;
    esac
}

for file in "$@"; do
	show "$file"
done

