#!/bin/bash

function guesstype() {
	executor=$(cat c | head -n1 | egrep '#!' | sed -e 's/#!//')
	last=${executor##*/}
	pygmentize -l $last $1
}

function show() {
	filename=$(basename -- "$1")
	extension="${filename##*.}"
	filename="${filename%.*}"

	case $extension in
		md) mdv $1
		;;
		*) pygmentize -Ostyle=friendly -g $1
		;;
	esac
}

while (( "$#" )); do
	show $1
	shift
done

