#!/usr/bin/env bash
# based on https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux


code="\033["
case $(echo $1 | tr '[:upper:]' '[:lower:]') in
  black  | bk) color="${code}0;30m";;
  red    |  r) color="${code}1;31m";;
  green  |  g) color="${code}1;32m";;
  yellow |  y) color="${code}1;33m";;
  blue   |  b) color="${code}1;34m";;
  purple |  p) color="${code}1;35m";;
  cyan   |  c) color="${code}1;36m";;
  gray   | gr) color="${code}0;37m";;
  *) text="$1"
esac
[ -z "$text" ] && text="$color${@: 2}${code}0m"
echo -e "$text"

