#!/usr/bin/env bash
# based on https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux


if [[ "$1" = "--help" ]]; then
    echo "Usage: cecho2 [options...] -- COLOR [text...]"
    echo "Example: cecho2 -n -- yellow No new line at the end of this line"
fi

options=()
color_name=
texts=()
text_part=false

while (( "$#" )); do
    if [[ $1 = "--" ]]; then
        text_part=true
        shift
        color_name="$1"
    elif [[ $text_part = false ]]; then
        options+=("$1")
    else
        texts+=("$1")
    fi

    shift
done

code="\033["
case $(echo "$color_name" | tr '[:upper:]' '[:lower:]') in
  black  | bk) color="${code}0;30m";;
  red    |  r) color="${code}1;31m";;
  green  |  g) color="${code}1;32m";;
  yellow |  y) color="${code}1;33m";;
  blue   |  b) color="${code}1;34m";;
  purple |  p) color="${code}1;35m";;
  cyan   |  c) color="${code}1;36m";;
  gray   | gr) color="${code}0;37m";;
  *) text="$1"
esac

printf -v text "%s " "${texts[@]}"
text="${color}${text}${code}0m"

printf -v option "%s " "${options[@]}"

echo -e $option "$text"

