#!/usr/bin/env bash

# clones urls like git@github.com:tavianator/bfs.git


sshformat='git@github.com:(.*)/(.*).git'
httpsformat='https://github.com/(.*)/(.*).git'
devDir="$HOME/dev"

function cloneit() {
    repogroup="$2"
    reponame="$3"
    basefolder="$devDir/$repogroup/"
    folder="$basefolder/$reponame"
    if [ ! -e "$folder" ]; then
        cecho cyan "Create $basefolder"
        mkdir -p "$basefolder"
        cd "$basefolder"
        echo git clone "$1" "$reponame"
        git clone "$1" "$folder"
    fi
}

if [[ $1 =~ $sshformat ]]; then
    cloneit "$1" "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"
elif [[ $1 =~ $httpsformat ]]; then
    cloneit "$1" "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"
else
    echo "Don't know how to clone $1"
fi

