#!/usr/bin/env bash

# clones urls like git@github.com:tavianator/bfs.git


format='git@github.com:(.*)/(.*).git'
devDir="$HOME/dev"

if [[ $1 =~ $format ]]; then
	repogroup="${BASH_REMATCH[1]}"
	folder="$devDir/$repogroup/${BASH_REMATCH[2]}"
	if [ ! -e "$folder" ]; then
		cecho cyan "Create $folder"
		mkdir -p "$folder"
		cd "$folder"
		echo git clone "$1" "$folder"
		git clone "$1" "$folder"
	fi
else
	echo "Don't know how to clone $1"
fi

