#!/usr/bin/env zsh

MYZONE="Indian/Reunion"
ZONES=("America/Mexico_City" "Europe/London" "Europe/Dublin" "Europe/Berlin" "Europe/Warsaw" "Indian/Reunion")

function pecho() {
    z=$1
    shift

    if [ $MYZONE = $z ]; then
        cecho green $@
    else
        echo $@
    fi

    return
}

function pdate() {
    z=$1
    shift
    pecho $z "$z\t-> $(TZ="$z" date $@)"
}

if [ $# -eq 0 ]; then

    for z ("$ZONES[@]"); do
        pdate $z
    done

else

    for z ("$ZONES[@]"); do
        utc_us=$(TZ="Etc/UTC" LC_TIME="" date --date="$@")
        pdate $z --date="${utc_us}"
    done

fi

exit 0
