#!/usr/bin/env bash

DOWNLOADS="$HOME/Downloads"
TRASH="$DOWNLOADS/archives"

if [ ! -d "$TRASH" ]; then
    mkdir "$TRASH"
fi

IFS=$'\n'
for f in $(ls -1tr "$DOWNLOADS" | head -n -9); do
    if [ "$f" != "archives" ]; then
        mv "$DOWNLOADS/$f" "$TRASH"
    fi
done

