#!/usr/bin/env sh

# sed escapes \... sequences, especially \0, so echo can show it properly and TEXT contains a literal \0 instead of the NULL character
TEXT=$(clipster -0 --output --number 100 2> /dev/null | sed -e 's/\\/\\\\/g' | fzf --read0 --print0 --preview "echo -n {}")

# Ctrl+C
if [ $? -eq 130 ]; then 
    exit 0
fi

# paste to all buffers
for selection in primary secondary clipboard
do
    echo -n "$TEXT" | xclip -selection $selection
done


