#!/usr/bin/env bash

selection=$(git branch --all | fzf)

case $? in
    0)
        git checkout $(echo "$selection" | trim)
        ;;
    1)
        cecho red "No match"
        ;;
    *)
        # Ctrl-C
        ;;
esac

