#!/usr/bin/env bash

GOPRO_BASE="/dev/disk/by-id/usb-SMI_USB_DISK_AA00000000015049-0:0-part1"
MOUNT="/mnt/gopro"
TARGET="$HOME/holygrenade/gopro/$(date +%F)"

mount | grep /mnt/gopro
if [ ! $? ]; then 
    sudo mount "/dev/disk/by-id/usb-SMI_USB_DISK_AA00000000015049-0:0-part1" "$MOUNT"
else
    cecho yellow "Already mounted"
fi

if [ ! -d "$TARGET" ]; then
    mkdir "$TARGET"
    mkdir "$TARGET/previews"
fi

echo green "Copying previews..."

for f in $(ls "$MOUNT/DCIM/100GOPRO/"*".LRV"); do
    output="$TARGET/previews/"$(basename -- "$f")
    echo GREEN "Copying $f to $output..."
    pv "$f" > "$output"
done

echo green "Copying videos"

for f in $(ls "$MOUNT/DCIM/100GOPRO/"*".MP4"); do
    output="$TARGET/"$(basename -- "$f")
    echo GREEN "Copying $f to $output..."
    pv "$f" > "$output"
done


