#!/usr/bin/env bash

TARGET="$HOME/holygrenade/gopro/$(date +%F)"

mkdir -p "$TARGET"
cecho yellow "$TARGET"

# Copy videos
cecho green "Copying videos"

for f in $(ls "$1"); do
    if [[ "$f" =~ .*\.MP4 ]]; then
        output="$TARGET/"$(basename -- "$f")
        cecho green "Copying $f to $output..."
        pv "$f" > "$output"
    # else skip that file
    fi
done

exit 0

