#!/bin/sh
# adapted from https://github.com/LukeSmithxyz/voidrice/blob/9524786a864ee3614e37ab260e413c3eaadf78fd/.scripts/i3cmds/dmenuunicode
# Give rofi list of all unicode characters to copy.

chosen="$(rofi -dmenu < ~/.resources/nerdfonts)"

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ - .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard

