#!/usr/bin/env bash


selection=$(clipster -0 --output --number 100 | tr --delete '\n' | rofi -dmenu -sep '\0')

grepIndex=$(clipster --output --number 100 -0 | tr --delete '\n' | tr '\0' '\n' | grep --fixed-strings "${selection}" --line-number | cut -d':' -f1 | head -n 1)

index=$(echo $grepIndex - 1 | bc)

# notify-send test "Index=$index"

for selection in primary secondary clipboard
do
    clipster -0 --output --position $index | tr --delete '\0' | xclip -selection $selection
done

