#!/usr/bin/env bash

filename=$(basename -- "$1")
extension="${filename##*.}"

unzipdir="/tmp"

case "$extension" in
    class) 
        major=$(javap -verbose "$1" | grep major)
        classversion "$major"
        ;;
    jar)
        [ ! -d "$unzipdir" ] && mkdir "$unzipdir"
        cecho GREEN "Unzipping..."
        unzip -q -o "$1" -d "$unzipdir/$filename"
        fd . --extension class "$unzipdir/$filename" | xargs javap -verbose | grep --text major | sort -r | uniq
        rm -rf "${unzipdir:?}/${filename:?}" 
        ;;
    *) cecho RED "Don't know how to read $1"
        ;;
esac
