#!/usr/bin/env bash

filename=$(basename -- "$1")
extension="${filename##*.}"

unzipdir='/mnt/ramdisk/unzip/'

function classversion() {
    regex=".*major version: ([0-9]+).*"
    if [[ "$1" =~ $regex ]]; then
        echo "Java $(echo "${BASH_REMATCH[1]} - 44" | bc)"
    fi
}


case "$extension" in
    class) 
        major=$(javap -verbose "$1" | grep major)
        classversion "$major"
        ;;
    jar)
        [[ ! -d "$unzipdir" ]] && mkdir "$unzipdir"
        cecho GREEN "Unzipping..."
        unzip -q -o "$1" -d "$unzipdir/$filename"
        IFS='\n'
        for line in "$(fd . --extension class "$unzipdir/$filename" | xargs javap -verbose | grep --text major | sort | uniq)"; do
            classversion "$line"
        done
        rm -rf "$unzipdir/$filename" 
        ;;
    *) cecho RED "Don't know how to read $1"
        ;;
esac
