#!/usr/bin/env sh

newfile="$HOME/dev/ununhexium/configfiles/.local/scripts/$1"

if [ -e "$newfile" ]; then
    echo "Skipping: file $newfile exists"
    exit 1
fi


echo "#!/usr/bin/env bash" > "$newfile"
chmod u+x "$newfile"

ln -s "$newfile" "$HOME/.local/bin/$1"

vi "$newfile"


