#!/usr/bin/env bash

here=$PWD

IFS=$'\n'
for dir in $(find -name ".git" -not -path ".git"); do
	cd "$here/$(dirname "$dir")" || exit 1
	git update-index -q --refresh
	if [[ $(git status --porcelain) ]]; then 
			cecho cyan "$PWD"
			git "$@"
	fi
done

