#!/usr/bin/env bash
if [[ -z $1 ]] || [[ $1 == "-" ]]; then
    input=$(mktemp)
    trap "rm -f $input" EXIT
    cat /dev/stdin > $input
else
    input=$1
fi

echo '' \
    | fzf --phony \
          --preview-window='up:90%,wrap' \
          --print-query \
          --preview "sed --regexp-extended -e s/{q}/❗/g $input > /tmp/sedrepl ; diff --unified $input /tmp/sedrepl | diff-highlight"
