#!/usr/bin/env bash

# Request sudo ahead of time with a "noop" task
sudo cat /dev/null

echo "Disabling swap..."
sudo swapoff -a &

until cat /proc/meminfo | grep -E -i "SwapTotal: +0 kB"
do
    cat /proc/meminfo | grep -i "SwapTotal"
    sleep 1
done

echo "Enabling swap..."
sudo swapon -a

cat /proc/meminfo | grep -i "swap"

