#!/bin/bash

val=$(/usr/lib/update-notifier/apt-check 2>&1)
#val="10;15"
#val="10;0"

normal=$(echo $val | cut -d';' -f1)
security=$(echo $val | cut -d';' -f2)

output=""
if [ $security -ne 0 ]; then
	indicator=""
	if [ $normal -ne 0 ]; then
		indicator="<sup><span foreground='#FF00FF'>+$normal</span></sup>"
	fi
	output="<span foreground='#FF00FF'> </span><span font_weight='bold' foreground='#FF00FF'>${security}$indicator</span>"
	notify-send --urgency critical "$security Security updates available"
elif [ $normal -ne 0 ]; then
	output="<span foreground='#00FFFF'> $normal</span>"
fi

echo "$output"

exit 0
