#!/usr/bin/env bash

if [[ $BLOCK_BUTTON -eq 1 ]]
then
  notify-send 'Time' "$(date)"
elif [[ $BLOCK_BUTTON -eq 3 ]]  
then
  notify-send 'Calendar' "$(cal)"
fi

icon=(           )
#icon_index=$(echo "$(date +%I) % 12" | bc)
offset_date=$(date -d @$(echo "$(date +%s) + 30*60" | bc) +%I)
icon_index=$(echo "$offset_date % 12" | bc)

now="<span size='xx-large'>${icon[$icon_index]}</span> $(date '+%H:%M')"

echo "$now"
echo "$now"

late="22:[3-5]."
verylate="2[3-4]:.*"

[[ $now =~ $late ]] &&  echo "#00FFFF"
[[ $now =~ $verylate ]] &&  echo "#FF00FF"

exit 0

