#!/usr/bin/env bash

if [[ $BLOCK_BUTTON -eq 1 ]]
then
  notify-send 'Time' "$(date)"
elif [[ $BLOCK_BUTTON -eq 3 ]]  
then
  notify-send 'Calendar' "$(cal)"
fi

now="$(date '+%H:%M')"

echo "$now"
echo "$now"

late="22:[3-5]."
verylate="2[3-4]:.*"

[[ $now =~ $late ]] &&  echo "#00FFFF"
[[ $now =~ $verylate ]] &&  echo "#FF00FF"

exit 0

