#!/bin/bash

command cargo --quiet > /dev/null && return

function cargoi() {
    for var in "$@"; do
        cargo install --list | grep "$var" || cargo install "$var"
    done
}   

echo "Installing rust dependencies"

command cargo --quiet > /dev/null || curl https://sh.rustup.rs -sSf | sh -s -- -y || exit 1

source "$HOME/.cargo/env"

cargoi \
    bat \
    fd-find \
    hexyl \
    lsd \
    ripgrep


